export const worksData = [
    { id: 1, slug: 'dirty-angels', title: 'Dirty Angels', image: '/works/dirty-angels.png', hoverImage: '/works/derTy.angel.cover.jpg', video: '/works/derTy.angel.mp4', category: 'Feature Film', role: 'Production Services', description: 'An intense action thriller directed by Martin Campbell starring Eva Green.', director: 'Martin Campbell', year: '2024', duration: '110 min' },
    { id: 2, slug: 'agent-vinod', title: 'Agent Vinod', image: '/works/agent-vinod.jpg', hoverImage: '/works/Agent.Vinod.cover.jpg', category: 'Feature Film', role: 'Line Production (Morocco)', description: 'A Bollywood spy thriller starring Saif Ali Khan with breathtaking action sequences.', director: 'Sriram Raghavan', year: '2012', duration: '157 min' },
    { id: 3, slug: 'emir', title: 'Emir', image: '/works/Emir.jpg', hoverImage: '/works/emir.webp', category: 'Feature Film', role: 'Line Production', description: 'An epic Philippine musical drama showcasing breathtaking Moroccan landscapes.', director: 'Chito S. Roño', year: '2010', duration: '125 min' },
    { id: 4, slug: 'okuotoko', title: 'Okuotoko', image: '/works/okuotoko.jpg', hoverImage: '/works/okuotoko.cover.jpg', category: 'Feature Film', role: 'Production Services (Morocco)', description: 'A Japanese drama exploring wealth and happiness, shot in the vibrant heart of Morocco.', director: 'Keishi Otomo', year: '2018', duration: '116 min' },
    { id: 5, slug: 'aazaan', title: 'Aazaan', image: '/works/Aazaan.png', hoverImage: '/works/azzan.cover.jpg', category: 'Feature Film', role: 'Production Services', description: 'A fast-paced Bollywood action movie involving international espionage.', director: 'Prashant Chadha', year: '2011', duration: '125 min' },
    { id: 6, slug: 'clash-of-the-gods', title: 'Clash of the Gods', image: '/works/clash.of.the.god.jpg', category: 'TV Series', role: 'Production Services', description: 'A mythological documentary series delving into ancient legends and epic landscapes.', director: 'Unknown', year: '2009', duration: '45 min/ep' },
    { id: 7, slug: 'black-angel', title: 'Black Angel', image: '/works/black.angel.jpg', category: 'Short Film', role: 'Production Services', description: 'A visually captivating fantasy project seamlessly facilitated by our local team.', director: 'Roger Christian', year: '2019', duration: '25 min' },
    { id: 8, slug: 'cia-confidential', title: 'CIA Confidential', image: '/works/CIA CONFIDENTIAL.jpg', category: 'TV Series / Docu-drama', role: 'Production Services', description: 'A tense docu-drama series recreating historical intelligence missions.', director: 'Various', year: '2010', duration: '60 min/ep' },
    { id: 9, slug: 'pegase', title: 'Pegase', image: '/works/pegase.jpg', category: 'Feature Film', role: 'Executive Production', description: 'An award-winning Moroccan psychological drama directed by Mohamed Mouftakir.', director: 'Mohamed Mouftakir', year: '2010', duration: '104 min' },
    { id: 10, slug: 'daag', title: 'DAAG', image: '/works/DAAG.jpg', category: 'Feature Film', role: 'Production Services', description: 'Cinematic feature relying on our extensive local network for logistical support.', director: 'Various', year: '2015', duration: 'N/A' },
    { id: 11, slug: 'flirt', title: 'Flirt', image: '/works/Flirt.png', hoverImage: '/works/flirt.cover.jpg', category: 'Feature Film', role: 'Production Services', description: 'A dramatic feature utilizing vibrant Moroccan cityscapes and distinct cultural backdrops.', director: 'Hal Hartley', year: '1995', duration: '85 min' },
    { id: 12, slug: 'garden-of-aden', title: 'Garden of Aden', image: '/works/garden-of-aden.png', category: 'Feature Film', role: 'Production Services', description: 'A deeply visual story supported by top-tier local crew and specialized equipment.', director: 'Alessandro D\'Alatri', year: '1998', duration: '95 min' },
    { id: 13, slug: 'midnight-fly', title: 'Midnight Fly', image: '/works/midnight-fly.png', hoverImage: '/works/Midnight.Fly.cover.jpg', category: 'Feature Film', role: 'Line Production', description: 'A thrilling feature requiring complex line production across challenging terrains.', director: 'Jacob Cheung', year: '2001', duration: '115 min' },
    { id: 14, slug: 'the-walk', title: 'The Walk', image: '/works/the-walk.png', category: 'Commercial / Short', role: 'Production Services', description: 'A high-end commercial project demanding rapid turnaround and flawless execution.', director: 'Robert Zemeckis', year: '2015', duration: '123 min' }
];

export function getWorkBySlug(slug: string) {
    return worksData.find((work) => work.slug === slug) || null;
}
